## 28일차 강의 (2021.8.11)
# 신경망

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot

In [2]:
np.exp(-20)/((1+np.exp(-20))**2)

2.061153613941849e-09

In [13]:
z = np.array([10, -3, -2])

In [14]:
np.exp(z)/np.exp(z).sum()

array([9.99991596e-01, 2.26031041e-06, 6.14416071e-06])

### 연습문제
- 아이리스 데이터에 선형회귀를 적용하고, 마지막 활성화함수로 소프트맥스를 적용한다.
- 이 경우, 최종 확률값을 구하고 크로스엔트로피도 구해보시오.
> 가중치와 절편값은 임의로 정한다.

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()

In [16]:
X = iris.data
y = iris.target

In [17]:
W = np.random.randn(4,3)/10 # np.random.normal(0,0.1,size=[4,3])
b = np.random.randn(3)/10

In [18]:
z = X@W + b
z.shape

(150, 3)

In [20]:
z0 = z[0]
z0

array([-0.23266011,  0.43489063, -0.71254672])

In [21]:
np.exp(z0)/np.exp(z0).sum()

array([0.28024469, 0.54632489, 0.17343042])

In [24]:
pred_y = np.exp(z)/(np.exp(z).sum(axis=1).reshape(150,1))
pred_y.shape

(150, 3)

In [25]:
pred_y.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
pred_y[0]

array([0.28024469, 0.54632489, 0.17343042])

In [27]:
y[0]

0

In [28]:
# 첫번째 샘플의 크로스엔트로피
-np.log(pred_y[0,y[0]])

1.272092181267184

In [29]:
entropy = 0
for i in range(150):
    entropy += -np.log(pred_y[i, y[i]])
    
entropy /= 150
entropy

1.3115254531808973

In [31]:
-np.log(pred_y[range(150), y]).mean()

1.3115254531808975

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
a = pred_y * np.eye(3)[y]
-np.log(a[a!=0]).mean()

1.3115254531808975