## 29일차 강의 (2021.8.12)
# 신경망

### 연습문제
아래는 신경망의 출력값이다. 소프트맥스를 이용해 확률값으로 변환하시오.
- [-1,0,1]
- [1,2,3]
- [10,20,30]
- [101,102,103]
- [[10,5,0], [-3,-2,-1],[0,0,1]]

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
pred_y = np.array([101,102,103])
np.exp(pred_y)/np.exp(pred_y).sum()

array([0.09003057, 0.24472847, 0.66524096])

In [6]:
np.exp(2)/np.exp(1)

2.7182818284590455

In [7]:
np.exp(101)/np.exp(100)

2.718281828459045

In [8]:
pred_y = np.array([10,20,30])
np.exp(pred_y)/np.exp(pred_y).sum()

array([2.06106005e-09, 4.53978686e-05, 9.99954600e-01])

In [10]:
pred_y = np.array([[10,5,0], [-3,-2,-1], [0,0,1]])
(np.exp(pred_y)/(np.exp(pred_y).sum(axis=1).reshape(3,1))).round(3)

array([[0.993, 0.007, 0.   ],
       [0.09 , 0.245, 0.665],
       [0.212, 0.212, 0.576]])

## 텐서플로 기초

In [11]:
import tensorflow as tf

In [12]:
from tensorflow import keras

In [13]:
tf.__version__

'2.4.0'

In [14]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 10231693457380349369,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 1408043828
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 5536760487950113917
 physical_device_desc: "device: 0, name: NVIDIA GeForce MX250, pci bus id: 0000:58:00.0, compute capability: 6.1"]

### 상수

In [15]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [18]:
a.numpy()

3

In [19]:
a = tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [20]:
a.numpy()

array([1, 2, 3])

In [21]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [22]:
a = a + 1
a

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [24]:
a = np.array([1,2,3])
b = a + 1
display(a,b)

array([1, 2, 3])

array([2, 3, 4])

In [25]:
a = np.array([1,2,3])
a = a + 1
a

array([2, 3, 4])

In [27]:
a = tf.constant(np.ones([4,3]))
a

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])>

In [28]:
a.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
tf.random.normal([4,3], 0, 1)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.1266607 ,  0.96471614,  0.48061278],
       [-0.6638771 , -0.9400132 ,  1.2567297 ],
       [-0.9625394 , -0.03231797, -1.798261  ],
       [-0.25040996,  0.55597377,  0.41470945]], dtype=float32)>

### 변수

In [30]:
x = tf.Variable(3)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [31]:
x + 1

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [33]:
x = x + 1
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [35]:
x = tf.Variable(3)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [36]:
x.assign(100)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [37]:
x.assign(x+1)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=101>

In [38]:
x.assign_add(33)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=134>

In [39]:
x.assign_sub(34)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

### 기울기 계산 (미분)

In [40]:
x = tf.Variable(1.0) # 변수 정의

with tf.GradientTape() as tape: # 미분할 함수 정의
    y = x**2
    
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [44]:
x = tf.Variable(0.0)

with tf.GradientTape() as tape:
    y = tf.exp(x)
    
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [45]:
tape.gradient(y,x)

RuntimeError: A non-persistent GradientTape can only be used tocompute one set of gradients (or jacobians)

In [46]:
x = tf.Variable(0.0)

with tf.GradientTape(persistent=True) as tape:
    y = tf.exp(x)
    
tape.gradient(y, x)
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [50]:
x = tf.Variable(1.0)

with tf.GradientTape(persistent=True) as tape:
    y = x**2
    z = x*y
    
tape.gradient(z, x)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [49]:
x = tf.Variable(1.0)

with tf.GradientTape(persistent=True) as tape:
    y = x**2
    z = x*y
    
tape.gradient(z, y) # y 에 대한 편미분

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

### 활성화함수

In [56]:
tf.nn.sigmoid(-100.)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [57]:
tf.nn.sigmoid([-10., 0., 10.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4.5397872e-05, 5.0000000e-01, 9.9995458e-01], dtype=float32)>