# 4일차 강의
## 파이썬 기초
- 2021.7.8

In [3]:
f = open('학생들.txt', encoding='utf-8') # utf-8(범용표준), cp949(윈도우)

In [4]:
s = f.readline()
s

'홍길동,22,원주\n'

In [8]:
f.close()

In [ ]:
data = [['홍길동',22,'원주'],
        ['장길산',33,'춘천'],
        ['둘리',5,'우주']]

In [9]:
f = open('학생들.txt', encoding='utf-8') # utf-8(범용표준), cp949(윈도우)

In [19]:
f = open('학생들.txt', encoding='utf-8') # utf-8(범용표준), cp949(윈도우)data = []

data = []

for line in f:
    l = line.strip().split(',')
    if l[1]=='':
        l[1]=-1
    else:
        l[1] = int(l[1])
        
    l[0]=l[0].strip('"')
    data.append(l)
    
f.close()

data

IndexError: list index out of range

In [15]:
int('')

ValueError: invalid literal for int() with base 10: ''

In [60]:
f = open('iris.csv')

In [61]:
s = f.readline()
header = s.strip().split(',')

labels = {'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}
labels2 = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [62]:
iris = [ ]

In [63]:
for line in f:
    l = line.strip().split(',')
    #l = [float(l[0]), float(l[1]), float(l[2]), float(l[3]), labels[l[4]]]
    #l = [float(l[0]), float(l[1]), float(l[2]), float(l[3]), labels2.index(l[4])]
    l = [float(l[i]) for i in range(4)] + [labels2.index(l[4])]
    iris.append(l)

In [64]:
f.close()

In [65]:
iris

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.4, 3.7, 1.5, 0.2, 0],
 [4.8, 3.4, 1.6, 0.2, 0],
 [4.8, 3.0, 1.4, 0.1, 0],
 [4.3, 3.0, 1.1, 0.1, 0],
 [5.8, 4.0, 1.2, 0.2, 0],
 [5.7, 4.4, 1.5, 0.4, 0],
 [5.4, 3.9, 1.3, 0.4, 0],
 [5.1, 3.5, 1.4, 0.3, 0],
 [5.7, 3.8, 1.7, 0.3, 0],
 [5.1, 3.8, 1.5, 0.3, 0],
 [5.4, 3.4, 1.7, 0.2, 0],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.6, 3.6, 1.0, 0.2, 0],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.0, 3.0, 1.6, 0.2, 0],
 [5.0, 3.4, 1.6, 0.4, 0],
 [5.2, 3.5, 1.5, 0.2, 0],
 [5.2, 3.4, 1.4, 0.2, 0],
 [4.7, 3.2, 1.6, 0.2, 0],
 [4.8, 3.1, 1.6, 0.2, 0],
 [5.4, 3.4, 1.5, 0.4, 0],
 [5.2, 4.1, 1.5, 0.1, 0],
 [5.5, 4.2, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.0, 3.2, 1.2, 0.2, 0],
 [5.5, 3.5, 1.3, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.4, 3.0, 

In [69]:
X = []
y = []

for l in iris:
    X.append(l[:-1])
    y.append(l[-1])

In [71]:
print(*y) # print(y[0],y[1],...,y[149])

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2


In [72]:
import myf # myf.py

In [ ]:
'''def myf1():
    print('hello')

def myf2(n):
    return n+1'''

In [73]:
myf.myf1()

hello


In [75]:
myf.myf2(99)

100

In [76]:
import os
os.getcwd()

'c:\\김현호'

In [77]:
import math
math.sin(3)

0.1411200080598672

In [78]:
from math import sin
sin(3)

0.1411200080598672

In [79]:
import numpy
numpy.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
dir(os)

['DirEntry',
 'F_OK',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_putenv',
 '_unsetenv',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen

In [86]:
l = ['홍길동','장길산','둘리']

In [87]:
for i in l:
    print(i)

홍길동
장길산
둘리


In [88]:
for i,v in enumerate(l):
    print(i,v)

0 홍길동
1 장길산
2 둘리


In [89]:
n = 0
for i in l:
    print(n, i)
    n += 1

0 홍길동
1 장길산
2 둘리


In [90]:
l1 = ['홍길동','장길산','둘리']
l2 = [22,33,5]

In [92]:
for name,age in zip(l1,l2):
    print(name,age)

홍길동 22
장길산 33
둘리 5


In [93]:
for i, (name,age) in enumerate(zip(l1,l2)):
    print(i,name,age)

0 홍길동 22
1 장길산 33
2 둘리 5


# 파이썬 데이터분석
- 데이터분석 : 많은 데이터에서 유용한 정보를 뽑아낸다
- 질서, 패턴 등을 찾는것

### 데이터분석 라이브러리
- Numpy : 주로 숫자형 데이터를 잘 처리한다
- Pandas : 표형태의 데이터 처리
- Matplotlib : 시각화 (그래프 그리기)
> - numpy가 중요한 이유 : list => numpy => tensorflow tensor (숫자를 주로 다룸)
> - pandas가 중요한 이유 : 데이터 로딩/전처리/코드화 => numpy로 넘김

In [94]:
import numpy as np

In [95]:
l = [[1,2,3], [2,3,4], [3,4,5]]

In [96]:
a = np.array(l)
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [98]:
a[1, 2] # 행번호, 열번호

4

In [99]:
type(a) # ndarray -> n-dimensional array

numpy.ndarray

In [100]:
f = open('iris.csv')

s = f.readline()
header = s.strip().split(',')

labels = {'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}
labels2 = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

iris = [ ]

for line in f:
    l = line.strip().split(',')
    #l = [float(l[0]), float(l[1]), float(l[2]), float(l[3]), labels[l[4]]]
    #l = [float(l[0]), float(l[1]), float(l[2]), float(l[3]), labels2.index(l[4])]
    l = [float(l[i]) for i in range(4)] + [labels2.index(l[4])]
    iris.append(l)

f.close()

In [102]:
iris_array = np.array(iris)
iris_array

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [104]:
iris_array.mean(axis=0)

array([5.84333333, 3.054     , 3.75866667, 1.19866667, 1.        ])

In [106]:
m = [0,0,0,0]
for l in iris:
    for i in range(4):
        m[i] += l[i]
        
for i in range(4):
    m[i] /=150

In [107]:
m

[5.843333333333335, 3.0540000000000007, 3.7586666666666693, 1.1986666666666672]

In [108]:
np.array([1,3,7,2,9])

array([1, 3, 7, 2, 9])

In [109]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [111]:
a = np.zeros([10,10])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [112]:
a[3,1] = 1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [113]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [115]:
np.arange(-1,1,0.1)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [116]:
np.arange(-1,1.000001,0.1)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01,
        1.00000000e+00])

In [117]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [118]:
np.random.rand(3,5) # 0~1 사이의 실수값을 랜덤하게 뽑는다

array([[0.36568757, 0.49220724, 0.6571256 , 0.57874464, 0.92388803],
       [0.86899541, 0.26657583, 0.80024775, 0.07110945, 0.70571635],
       [0.24995764, 0.7780983 , 0.68356925, 0.45533691, 0.59290823]])

In [119]:
l = [[1], [2,3],[4,5,6]]
l

[[1], [2, 3], [4, 5, 6]]

In [120]:
np.array(l)

<ipython-input-120-8f9696ebb44b>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array(l)


array([list([1]), list([2, 3]), list([4, 5, 6])], dtype=object)

In [121]:
l = [1, 1.0, -1.0, '일']
l

[1, 1.0, -1.0, '일']

In [122]:
np.array(l)

array(['1', '1.0', '-1.0', '일'], dtype='<U32')

### 어레이의 특징
- 직사각형(정방형) 모양만 된다 => 행의 갯수, 열의 갯수
- 한가지 타입만 가진다 => 정수/실수/bool 중의 하나다

In [125]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [126]:
a.shape # 튜플

(3, 4)

In [133]:
b = np.array([1])
print(b)
print(b.shape)

[1]
(1,)


In [134]:
a.shape[0], a.shape[1]

(3, 4)

In [136]:
len(a), len(a[0])

(3, 4)

In [127]:
a.dtype # float64 는 8바이트 실수라는 의미

dtype('float64')

In [128]:
np.float64

numpy.float64

In [129]:
np.float32

numpy.float32

In [131]:
np.float16

numpy.float16

In [132]:
np.ones([3,4], dtype=np.float16)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)

In [137]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a[3]

3

In [139]:
a[3:7]

array([3, 4, 5, 6])

In [140]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
a[1][1]

5

In [142]:
a[1, 1]

5

In [143]:
a[1]

array([4, 5, 6, 7])

In [144]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [145]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [146]:
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [147]:
a[1:3, 3]

array([ 7, 11])

In [148]:
a[1:3, 3:]

array([[ 7],
       [11]])