In [1]:
m = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
li = [j  for i in m for j in range(1, i+1)]
import numpy as np
import datetime
cal = np.array([0, 0, 0, 0, 0, 0]+li).reshape(-1,7)
yoil = ["Su","Mo", "Tu", "We", "Th", "Fr", "Sa"]
iljung = {400:['x','y','z']}
len(cal.flatten())

371

In [2]:
## 달력출력
def toomonth(x):
    z = 0
    for i in range(371):
        if z == x:
            if x in (1, 7, 10):
                print("{}월".format(x))
                print(" ", " ".join(yoil))
                print(cal[(z//7):(z//7)+6,:])
                break
            else:
                print("{}월".format(x))
                print(" ", " ".join(yoil))
                print(cal[(z//7):(z//7)+5,:])
                break
        elif cal.flatten()[i] == 1:
            z += 1

In [3]:
## 일정표
def iljong_in(x, y, z):
    k=0
    for i in range(x):
        k += m[i]
    k += y
    if k in list(iljung.keys()):
        if iljung[k] == None:
            del iljung[k]
            iljung[k] = z
        elif type(iljung[k]) == str:
            iljung[k] = [iljung[k]]+[z]
        else:
            iljung[k] = iljung[k]+[z]
    else:
        iljung[k] = z

def iljong_out(x, y):
    k=0
    for i in range(x):
        k += m[i]
    k += y
    if k in list(iljung.keys()):
        print(iljung[k])
    else:
        print('일정이 없습니다.')

In [9]:
def tooday():
    print(datetime.datetime.now())
    k = sum(m[0 : int(str(datetime.datetime.now())[5:7])]) + int(str(datetime.datetime.now())[8:10])
    if k in list(iljung.keys()):
        print("금일 일정")
        print(iljung[k])
    else:
        print('일정이 없습니다.')

In [10]:
toomonth(4)

4월
  Su Mo Tu We Th Fr Sa
[[ 0  0  0  0  0  0  1]
 [ 2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29]]


In [11]:
iljong_in(5, 19, 'hello, world')

In [12]:
tooday()

2022-05-19 09:20:09.424829
금일 일정
['hello, world', 'hello, world']
