In [14]:
import numpy as np
import torch
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import dataset


In [2]:
xy = np.loadtxt('./data-03-diabetes.csv',delimiter=',', dtype = np.float32)

In [3]:
print(xy)

[[-0.294118   0.487437   0.180328  ... -0.53117   -0.0333333  0.       ]
 [-0.882353  -0.145729   0.0819672 ... -0.766866  -0.666667   1.       ]
 [-0.0588235  0.839196   0.0491803 ... -0.492741  -0.633333   0.       ]
 ...
 [-0.411765   0.21608    0.180328  ... -0.857387  -0.7        1.       ]
 [-0.882353   0.266332  -0.0163934 ... -0.768574  -0.133333   0.       ]
 [-0.882353  -0.0653266  0.147541  ... -0.797609  -0.933333   1.       ]]


In [26]:
x_data = xy[:,:-1] # 행렬

y_data = xy[:,[-1]]


x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


In [15]:

# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)
nb_epochs = 100
for epoch in range(nb_epochs + 1):
    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis,y_train) # 같다 ! / 
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward() # 미분 
    optimizer.step()
    # 100번마다 로그 출력
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.572727
Epoch   20/100 Cost: 0.539493
Epoch   30/100 Cost: 0.519708
Epoch   40/100 Cost: 0.507066
Epoch   50/100 Cost: 0.498539
Epoch   60/100 Cost: 0.492549
Epoch   70/100 Cost: 0.488209
Epoch   80/100 Cost: 0.484985
Epoch   90/100 Cost: 0.482543
Epoch  100/100 Cost: 0.480661


In [16]:

# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)
nb_epochs = 100
for epoch in range(nb_epochs + 1):
    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) +
             (1 - y_train) * torch.log(1 - hypothesis)).mean()
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward() # 미분 
    optimizer.step()
    # 100번마다 로그 출력
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.250000
Epoch   10/100 Cost: 0.206335
Epoch   20/100 Cost: 0.195664
Epoch   30/100 Cost: 0.187775
Epoch   40/100 Cost: 0.181874
Epoch   50/100 Cost: 0.177382
Epoch   60/100 Cost: 0.173894
Epoch   70/100 Cost: 0.171133
Epoch   80/100 Cost: 0.168908
Epoch   90/100 Cost: 0.167088
Epoch  100/100 Cost: 0.165580


In [ ]:
# 정확도 파악 ! 

In [20]:
hypothesis = torch.sigmoid(x_train.matmul(W)+b)
prediction = hypothesis >= torch.FloatTensor([0.5])

print(prediction[:5])

tensor([[False],
        [ True],
        [False],
        [ True],
        [False]])


In [22]:
print(prediction[:5])
print(y_train[:5])

tensor([[False],
        [ True],
        [False],
        [ True],
        [False]])
tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])


In [ ]:
accuracy = correct