In [2]:
# softmax 

In [ ]:
# 확률값으로 던져준다. 그이야기는 클래스 n 개 있을때 확률 각각 더해서 1 되는 확률 값 
#  1 2 3 이라는 것은  , 

In [ ]:
# 0.09 , 0.2447 , 0.6652 / e 1 e 2  e 3 e 4  e 5 분의 e i 값  # 0이면 1 2면 20분의 7 /  

In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np 

In [47]:
torch.manual_seed(1)


In [48]:
print(np.exp(0))
print(np.exp(1))
print(np.exp(2))
print(np.exp(3))

1.0
2.718281828459045
7.38905609893065
20.085536923187668


In [49]:
#  np.exp 는 각 요소에 자연상수  e  를 밑으로 하는 지수함수 값을 반환합니다.

             ex)  np.exp(-z)  란...   e^(-z)    "e의 -z 승"
# [출처] np.exp(-z)  가 무슨 뜻일까?  (feat.넘파이 연산)|작성자 사이다

IndentationError: unexpected indent (1828881802.py, line 3)

In [50]:
np.exp(1) /(np.exp(1) + np.exp(2) + np.exp(3))

0.09003057317038046

In [51]:
z = torch.FloatTensor([1,2,3])
print(z)

tensor([1., 2., 3.])


In [52]:
hypothesis = torch.softmax(z, dim = 0)
print(hypothesis.sum())

tensor(1.)


In [53]:
# 가위 바위 보 가정 했을때 , 확률 값  p , 상대방이 보를 낼 확률 , 내가 가위를 낼 경우 , 상대방이 주먹을 낼 경우 ! ,/  
# 가위 바위 바구이 가위 가위 가장큰 값 전체 확률을 내준다 .


In [54]:
#이렇게 우리는 Multiclassification 에서의 Softmax 의 사용 그리고 Binary Classification 에서의 Sigmoid 활성화 함수에 대한 사용법에 대해서 알아보았습니다. 
#가장 중요한것은 softmax와 sigmoid 모두, logit 이 입력으로 들어오고, 이들의 확률이 출력으로 나타나는것이라고 할 수 있겠습니다.

#[출처] 딥러닝 이론 Sigmoid 와 SoftMax|작성자 바고

In [55]:
# softmax 정답값과 , 예측값 대해서 px 값 / 결국은 저값 , / p라는 그래프가 있는 것이고 , q 라는 그래프 , q1 , q2 ,, 

In [56]:
# h(p,q) # h(p,q2) 크게 되어 있다. 그때 차이 값을 p q 라고 한다. 

In [57]:
p(x) 변했을때 값 # 랜덤값 dim 1  2q번째 값 확률 값이 어떠냐? / 5는 값에서 클래스 

SyntaxError: invalid syntax (949980751.py, line 1)

In [58]:
# 원핫 인코딩 한다 ! , /// 가설치가 z 로 설정 3행 5열  토치로 하는데 3행 5열 딴다 . zero 값을 깔고, - 값은 # 0 , 2 1 로 해서 원핫 인코딩 구성을 해라 ! 

In [59]:
# torch.log 써서 코스트 값 구한 것 ! , 

In [60]:
z = torch.rand(3,5, requires_grad = True  )
hypothesis = torch.softmax(z, dim = 1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [61]:
y = torch.randint(5,(3,)).long() # 3행 5열 값 가짐 
print(y)

tensor([0, 2, 1])


In [62]:
y_one_hot = torch.zeros_like(hypothesis) # 3 , 5 
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [69]:
torch.log(F.softmax(z,dim = 1)) # 아래와 같은 값 

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward0>)

In [70]:
F.log_softmax(z , dim = 1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

In [65]:
#nll negative log likehood 

# 최종은 F.cross_entropy(z,y)

In [71]:
# low level
cost = (y_one_hot * - torch.log(hypothesis)).sum(dim=1).mean()
cost

tensor(1.4689, grad_fn=<MeanBackward0>)

In [67]:
# hgi level
F.nll_loss(F.log_softmax(z,dim = 1),y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [73]:
F.cross_entropy(z,y) # 가장 간단하게 할 수 있다 . ! /
# 전체 생략하고 쓰게 되면 , 다시 쓰게 되는 경우가 있다. 최종 손실만 필요하냐 , 아니면 확률 로직도 필요하냐에 따라서 다르다 ,

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [ ]:
# 클래스화 , 전체적으로 

In [74]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)
# 4차원에 들어가서 클래스 3개 , 4개가 들어가서 아웃풋은 3개를 만든다 .

In [75]:
# 모델 초기화 # x 4개 y 3개 
W = torch.zeros((4, 3), requires_grad=True)
b = torch.zeros(1,requires_grad=True)

In [79]:
optimizer = optim.SGD([W,b], lr = 0.1)

In [87]:
# low level 
epochs = 1000
for epoch in range(epochs+1):
    hypothesis = F.softmax(x_train.matmul(W)+b ,dim = 1)
    y_one = torch.zeros_like(hypothesis)
    y_one.scatter_(1, y_train.unsqueeze(1),1)
    cost = (y_one * -torch.log(F.softmax(z,dim = 1))).sum(dim = 1).mean()
    
    optimizer.zero_gard()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print('epoch {:4d}/{} Cost : {:.6f}'.format(
        epoch , epochs , cost.item()
        ))

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1

In [88]:
class SoftmaxclassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)
        
    def forward(self,x):
        return self.linear(x)
        


In [93]:
model = SoftmaxclassifierModel()
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [95]:
# high level 



epochs = 1000
for epoch in range(epochs+1):
    
    prediction = model(x_train)
  
    
    cost = F.cross_entropy(prediction,y_train)    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print('epoch {:4d}/{} Cost : {:.6f}'.format(
        epoch , epochs , cost.item()
        ))

epoch    0/1000 Cost : 1.845720
epoch  100/1000 Cost : 0.647150
epoch  200/1000 Cost : 0.568868
epoch  300/1000 Cost : 0.515699
epoch  400/1000 Cost : 0.471727
epoch  500/1000 Cost : 0.432486
epoch  600/1000 Cost : 0.395879
epoch  700/1000 Cost : 0.360507
epoch  800/1000 Cost : 0.325228
epoch  900/1000 Cost : 0.289217
epoch 1000/1000 Cost : 0.254086


RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1